export const apikey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3emhqY2d3a2JvcGt1ZGVvcmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA3NTE2NjgsImV4cCI6MjAyNjMyNzY2OH0.gzFbm6TxORoZRMcMhzBSMa_2PTh5EyIj9pCJ_CkXlDk";
export const endpoint = "https://dwzhjcgwkbopkudeordj.supabase.co/rest/v1/Recipes";
